### ISSUE TITLE
Invalid "state" of buffer when decoding string

### ISSUE THREAD

**Issue by marcstern** [robohack/yajl#3]
In yajl_parser.c, on line 258, we pass yajl_buf_data(hand->decodeBuf) to the callback instead of the usual buffer "buf". As this points to another memory location, the callback receive 2 buffers that are located in another space.
Concrete problem: in ModSecurity, we use the callback to get the decoded value of the string and we calculate the offset of a variable value in order to mask it in the log. In the callback, when the JSON is decoded, we receive another location than the original one and we cannot calculate the offset.

We could perform this trivial change:
```
-yajl_string_decode(hand->decodeBuf, buf, bufLen);
-_CC_CHK(hand->callbacks->yajl_string(
                                    hand->ctx, yajl_buf_data(hand->decodeBuf),
                                    yajl_buf_len(hand->decodeBuf)));
+if (yajl_string_decode(hand->decodeBuf, buf, bufLen) < 0) return yajl_status_error;
+bufLen = yajl_buf_len(hand->decodeBuf);
+strcpy((char*)buf, (char*)yajl_buf_data(hand->decodeBuf));
+_CC_CHK(hand->callbacks->yajl_string(hand->ctx, buf, bufLen));
```

Same on line 397

**Comment by robohack** [comment]
I'm not quite sure I understand the problem.

The proposed change can't be entirely right though as it adds a test for a `void` function's return value.

**Comment by marcstern** [comment]
Indeed, I assumed in this change that yajl_string_decode() was fixed to return a status, as it could fail.
I implemented this PR: https://github.com/lloyd/yajl/pull/151/files (which should be included) but my proposal stays valid without the return code check obviously.

**Comment by robohack** [comment]
Having done some more work with the lexer and parser in recent days I don't think I like this proposed change at all.  I really don't think it's a good idea to modify the original input in the lexer's buffer.  Having to use `__UNCONST()` to avoid the warnings that result is also big red flag.

I think there's a conflation of concerns in your callback implementations making assumptions about the objects being pointed to by their parameters.  The API doesn't make any guarantees about how those parameters are related to any other objects.  In fact some of the internal lexer documentation (description of `yajl_lex_lex(..., outBuf, ...)`) says the very opposite!   In theory all of the objects passed to the callbacks could be uniquely allocated to separate objects each in their own memory locations.  It's only an accident of optimization and implementation, _and_ how big each input chunk is, that sometimes they are within the input text and sometimes they're in another buffer that's reused for subsequent calls, and sometimes they're in yet another buffer allocated (and possibly frequently reused) by the lexer.
