### ISSUE TITLE
Enhancement: conditional define for alloc macros

### ISSUE THREAD

**Issue by marcstern** [robohack/yajl#4]
For enhanced performance in prod:
```
#ifdef NDEBUG
# define YA_MALLOC(afs, sz) malloc(sz)
# define YA_FREE(afs, ptr) free(ptr)
# define YA_REALLOC(afs, ptr, sz) realloc(ptr, sz)
#else
# define YA_MALLOC(afs, sz) (afs)->malloc((afs)->ctx, (sz))
# define YA_FREE(afs, ptr) (afs)->free((afs)->ctx, (ptr))
# define YA_REALLOC(afs, ptr, sz) (afs)->realloc((afs)->ctx, (ptr), (sz))
#endif
```

**Comment by robohack** [comment]
Two problems with that:

1. The API for the `yajl_alloc_funcs` mandates that they check for, and handle, any allocation (or usage) errors, so in production we definitely require those functions be used.
2. Avoiding the overhead of an indirect call is a job for the optimizer.
