### ISSUE TITLE
NULL pointer 2

### ISSUE THREAD

**Issue by marcstern** [robohack/yajl#6]
In yajl_alloc(), there no NULL pointer check after the YA_MALLOC:
```
hand = (yajl_handle) YA_MALLOC(afs, sizeof(struct yajl_handle_t));
+if (!hand) return NULL;
```

Same in yajl_lex_alloc():
```
yajl_lexer lxr = (yajl_lexer) YA_MALLOC(alloc, sizeof(struct yajl_lexer_t));
+if (!lxr) return NULL;

```

**Comment by robohack** [comment]
So, checking for `NULL` returns from `YA_MALLOC()` and friends is never necessary.  The API for the `yajl_alloc_funcs` mandates that they check for, and handle, any allocation (or usage) errors.
