### ISSUE TITLE
Memory full problem

### ISSUE THREAD

**Issue by marcstern** [robohack/yajl#8]
Ther was a PR that solves a memory allocation problem being undetected:
https://github.com/lloyd/yajl/pull/151/files

This should really be incorporated

**Comment by robohack** [comment]
So, checking for `NULL` returns from `YA_MALLOC()` and friends is never necessary.  The API for the `yajl_alloc_funcs` mandates that they check for, and handle, any allocation (or usage) errors.

**Comment by marcstern** [comment]
How to handle an allocation error?
We cannot gracefully break the flow, unless aborting the whole program.
Furthermore, the default alloc functions in yajl_set_default_alloc_funcs() don't check for failure. We may expect a lot of applications using the default functions, no?

**Comment by robohack** [comment]
If you're out of memory aborting is usually the only sane course of action.  It's just a question of how graceful you (need to) make the abort.

I'll try adding as an example a simple way to do a more graceful abort to the test and example programs.

In theory you could jump out of the parser andd then free just the parser and any partial results, keep the main program running, and then tell the user the input is un-parseable for some reason, though there's some risk the free operation might have undefined behaviour (though maybe it's simple enough to make it safe in all possible scenarios).

Indeed there may be many existing applications that just use the default allocators, though I'm not sure how best to fix them.  One must convince their maintainers to recompile them anyway, so why not also convince them to add custom allocators at the same time?

I did consider adding `abort(3)` calls to the default allocators to handle errors.  Perhaps that's still the best/safest idea.  At least it would avoid any undefined behaviour.

**Comment by marcstern** [comment]
One very practical example of parsing where we don't want to abort is in mod_security2. In case some one sends a too big/complex request, we want it to be rejected, not aborting the whole process serving many other clients.
